-- CreateEnum
CREATE TYPE "ApplicationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN');

-- CreateEnum
CREATE TYPE "ProjectVisibility" AS ENUM ('PUBLIC', 'PRIVATE', 'DRAFT');

-- AlterEnum - Add new NotificationType values
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROJECT_PUBLISHED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROJECT_APPLICATION';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPLICATION_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPLICATION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INFLUENCER_SELECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROJECT_STARTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROJECT_MILESTONE';

-- AlterEnum - Add new ProjectStatus values
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'OPEN';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'REVIEWING_APPLICATIONS';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'INFLUENCER_SELECTED';
